export const SCHOOLS = [
  "University of Texas at Austin",
  "University of Florida",
  "Texas A&M University",
  "University of California Los Angeles",
  "University of California Berkeley",
  "University of Michigan Ann Arbor",
  "University of Georgia",
  "Florida State University",
  "University of Central Florida",
  "University of California Irvine",
  "University of California San Diego",
  "Brigham Young University",
  "University of Illinois Urbana-Champaign",
  "Ohio State University",
  "University of North Carolina at Chapel Hill",
  "University of California Davis",
  "University of Wisconsin Madison",
  "New York University",
  "University of Maryland",
  "Pennsylvania State University",
  "University of South Florida",
  "University of Southern California",
  "Georgia Tech",
  "Michigan State University",
  "Virginia Tech",
  "University of Washington",
  "Arizona State University",
  "University of California Santa Barbara",
  "Purdue University",
  "North Carolina State University",
  "University of Virginia",
  "Stanford University",
  "Indiana University Bloomington",
  "University of California Riverside",
  "Cornell University",
  "University of Minnesota Twin Cities",
  "Baylor University",
  "University of Arizona",
  "Boston University",
  "University of Colorado Boulder",
  "University of Kentucky",
  "California Polytechnic State University",
  "Auburn University",
  "Rutgers University",
  "University of Arkansas",
  "Clemson University",
  "University of Miami",
  "Harvard University",
  "University of South Carolina",
  "Duke University",
"Northwestern University",
  "University of Oklahoma",
  "University of California Santa Cruz",
  "Massachusetts Institute of Technology",
  "University of Alabama",
  "California State University Long Beach",
  "Texas Tech University",
  "University of Notre Dame",
  "San Diego State University",
  "Florida International University",
  "James Madison University",
  "University of Houston",
  "Colorado State University",
  "University of Texas at San Antonio",
  "University of Tennessee Knoxville",
  "University of Texas Rio Grande Valley",
  "Rice University",
  "University of Pittsburgh",
  "University of North Texas",
  "Texas State University",
  "Vanderbilt University",
  "Northeastern University",
  "Louisiana State University",
  "University of Utah",
  "University of Delaware",
  "Washington University in St. Louis",
  "University of Missouri",
  "University of Chicago",
  "University of Massachusetts Amherst",
  "Boston College",
  "University of Cincinnati",
  "Miami University",
  "Georgia State University",
  "George Washington University",
  "University of Texas at Arlington",
  "University of Connecticut",
  "Emory University",
  "Virginia Commonwealth University",
  "University of Pennsylvania",
  "Appalachian State University",
  "Princeton University",
  "University of Illinois Chicago",
  "Georgetown University",
  "Columbia University",
  "University of Nevada Reno",
  "Brown University",
  "University of Oregon",
  "George Mason University",
  "University of Iowa",
  "Yale University","Syracuse University",
  "Miami Dade College",
  "Carnegie Mellon University",
  "Oklahoma State University",
  "University of San Diego",
  "Johns Hopkins University",
  "California State University Northridge",
  "Grand Valley State University",
  "Texas Christian University",
  "West Virginia University",
  "College of William and Mary",
  "University of Louisville",
  "University of North Florida",
  "Washington State University",
  "Oregon State University",
  "University of Texas at Dallas",
  "Loyola University Chicago",
  "United States Naval Academy",
  "Stony Brook University",
  "Utah State University",
  "Iowa State University",
  "San Francisco State University",
  "University of New Mexico",
  "California State University Fresno",
  "Rochester Institute of Technology",
  "Ball State University",
  "Northern Arizona University",
  "United States Air Force Academy",
  "Binghamton University",
  "Southern Methodist University",
  "Temple University",
  "Florida Atlantic University",
  "Tulane University",
  "Georgia Southern University",
  "University of North Carolina Wilmington",
  "DePaul University",
  "American University",
  "California State Polytechnic University Pomona",
  "Drexel University",
  "San Jose State University",
  "Wake Forest University",
  "College of Charleston",
  "East Carolina University",
  "United States Military Academy",
  "Western Washington University",
  "University of Maryland Baltimore County",
  "University of Kansas",
  "University of British Columbia",
  "Tufts University",
  "Dartmouth College","University at Buffalo",
  "Marquette University",
  "University of Nebraska Lincoln",
  "University of Nevada Las Vegas",
  "Case Western Reserve University",
  "Ohio University",
  "Santa Clara University",
  "Villanova University",
  "University of North Carolina Charlotte",
  "Towson University",
  "Western Kentucky University",
  "California State University Los Angeles",
  "University of Vermont",
  "Central Michigan University",
  "University of Texas at El Paso",
  "University of Central Arkansas",
  "University of Mississippi",
  "Rensselaer Polytechnic Institute",
  "University of California Merced",
  "Brigham Young University Idaho",
  "Fordham University",
  "Colorado School of Mines",
  "Savannah College of Art and Design",
  "Valencia College",
  "Florida A&M University",
  "Sam Houston State University",
  "University of Rochester",
  "Kennesaw State University",
  "Mississippi State University",
  "Loyola Marymount University",
  "University of Alabama at Birmingham",
  "Lehigh University",
  "Old Dominion University",
  "California State University Sacramento",
  "University of Hawaii at Manoa",
  "McGill University",
  "Florida Gulf Coast University",
  "Montana State University",
  "Illinois State University",
  "University of Wisconsin La Crosse",
  "University of Wisconsin Eau Claire",
  "University of the Pacific",
  "Indiana University Purdue University Indianapolis",
  "St. John's University",
  "Western Michigan University",
  "University of North Carolina Greensboro",
  "University of Denver",
  "SUNY Geneseo",
  "Williams College",
  "Amherst College","Swarthmore College",
  "Pomona College",
  "Wellesley College",
  "Bowdoin College",
  "Carleton College",
  "Middlebury College",
  "Claremont McKenna College",
  "Davidson College",
  "Washington and Lee University",
  "Hamilton College",
  "Vassar College",
  "Haverford College",
  "Colby College",
  "Colgate University",
  "Smith College",
  "Grinnell College",
  "Wesleyan University",
  "Harvey Mudd College",
  "Bates College",
  "Barnard College",
  "Macalester College",
  "Bryn Mawr College",
  "Oberlin College",
  "Kenyon College",
  "Scripps College",
  "Pitzer College",
  "Mount Holyoke College",
  "Colorado College",
  "Bucknell University",
  "Lafayette College",
  "Occidental College",
  "Trinity College",
  "Connecticut College",
  "Union College",
  "Skidmore College",
  "Denison University",
  "Whitman College",
  "Reed College",
  "Dickinson College",
  "Franklin & Marshall College",
  "Sewanee: The University of the South",
  "Furman University",
  "DePauw University",
  "Gettysburg College",
  "Rhodes College",
  "St. Olaf College",
  "Wheaton College (Massachusetts)",
  "Sarah Lawrence College",];